# Generated by Django 4.2.1 on 2023-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="researchpaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("year", models.IntegerField()),
                (
                    "record_type",
                    models.IntegerField(
                        choices=[
                            (1, "Proposal"),
                            (2, "Thesis/Research"),
                            (3, "Project"),
                        ]
                    ),
                ),
                (
                    "classification",
                    models.IntegerField(
                        choices=[(1, "Basic Research"), (2, "Applied Research")]
                    ),
                ),
                ("psc_ed", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
            ],
        ),
    ]
